name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZFAndroidABI: ${{secrets.ZFANDROIDABI}}
      ZF_PROJ_PATH: ZFLoader/zfproj/Android/ZFLoader
      ZF_PROJ_NAME: ZFLoader

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21e

    - name: ZF build zfproj
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/testbuild/testbuild_Android.sh
        ../ZFFramework/master/ZF_CI/testbuild/testbuild_Android.sh "${ZF_PROJ_NAME}" "${ZF_PROJ_PATH}"

    - name: ZF upload archive
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/upload_app.sh
        ../ZFFramework/master/ZF_CI/upload_app.sh "${ZF_PROJ_PATH}/Android/${ZF_PROJ_NAME}/zfapp/build/outputs/apk/release/zfapp-release.apk" "${ZF_PROJ_NAME}.apk"

