name: CMake MacOS

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: ZFLoader/zfproj
      ZF_PROJ_NAME: ZFLoader

    steps:
    - uses: actions/checkout@v4

    - name: get-cmake
      uses: lukka/get-cmake@latest

    - name: Set up NASM
      uses: ilammy/setup-nasm@v1

    - name: ZFSetup
      run: |
        chmod +x ./zfsetup.sh
        ./zfsetup.sh

    - name: ZF build zfproj
      run: |
        chmod +x ../ZFFramework/tools/buildapp/buildapp_cmake.sh
        ../ZFFramework/tools/buildapp/buildapp_cmake.sh "${ZF_PROJ_NAME}" "${ZF_PROJ_PATH}"

    - name: ZF zip archive
      uses: vimtor/action-zip@v1.2
      with:
          files: _tmp/cmake/${{env.ZF_PROJ_NAME}}/app/
          dest: _tmp/cmake/${{env.ZF_PROJ_NAME}}/app.zip

    - name: ZF upload archive
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/upload_app.sh
        ../ZFFramework/master/ZF_CI/upload_app.sh "_tmp/cmake/${ZF_PROJ_NAME}/app.zip" "cmake_MacOS/${ZF_PROJ_NAME}.zip"

