name: Qt MacOS

on:
  push:
    branches: [ "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    env:
      ZFCI_TOKEN: ${{secrets.ZFCI_TOKEN}}
      ZF_PROJ_PATH: demo/zfproj
      ZF_PROJ_NAME: ZFLoader

    steps:
    - uses: actions/checkout@v3

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3.0.0
      with:
        host: mac
        target: desktop
        modules: qtwebengine

    - name: ZFSetup
      run: |
        chmod +x ./zfsetup.sh
        ./zfsetup.sh

    - name: ZF build zfproj
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/testbuild/testbuild_Qt_MacOS.sh
        ../ZFFramework/master/ZF_CI/testbuild/testbuild_Qt_MacOS.sh "${ZF_PROJ_NAME}" "${ZF_PROJ_PATH}/Qt/${ZF_PROJ_NAME}"

    - name: ZF upload archive
      run: |
        chmod +x ../ZFFramework/master/ZF_CI/upload_app.sh
        ../ZFFramework/master/ZF_CI/upload_app.sh "./_tmp/Qt_MacOS/${ZF_PROJ_NAME}/release/${ZF_PROJ_NAME}.app" "${ZF_PROJ_NAME}.app"

